"""
vocabulary/urls.py
==================
URL patterns for all vocabulary app endpoints.

Mounted under /api/v1/ in config/urls.py.
"""

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    CollectionViewSet,
    ContributeCollectionView,
    ContributeWordView,
    SyncView,
    WordViewSet,
)

# DRF DefaultRouter auto-generates list/detail routes for ViewSets
router = DefaultRouter()
router.register(r"collections", CollectionViewSet, basename="collection")
router.register(r"words", WordViewSet, basename="word")

urlpatterns = [
    # -------------------------------------------------------------------
    # Core sync endpoint — the heart of offline-first architecture
    # GET /api/v1/sync/?last_synced_at=<timestamp>
    # -------------------------------------------------------------------
    path("sync/", SyncView.as_view(), name="sync"),

    # -------------------------------------------------------------------
    # Read-only browsing routes (generated by router):
    #   GET /api/v1/collections/
    #   GET /api/v1/collections/<id>/
    #   GET /api/v1/collections/<id>/words/
    #   GET /api/v1/words/
    #   GET /api/v1/words/<id>/
    # -------------------------------------------------------------------
    path("", include(router.urls)),

    # -------------------------------------------------------------------
    # Authenticated contribution endpoints
    #   POST /api/v1/contribute/words/
    #   POST /api/v1/contribute/collections/
    # -------------------------------------------------------------------
    path("contribute/words/", ContributeWordView.as_view(), name="contribute-word"),
    path(
        "contribute/collections/",
        ContributeCollectionView.as_view(),
        name="contribute-collection",
    ),
]
