# Generated by Django 6.0.3 on 2026-06-28 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique identifier — safe to generate offline.', primary_key=True, serialize=False)),
                ('name_uz', models.CharField(help_text='Collection name in Uzbek.', max_length=255, verbose_name='Name (Uzbek)')),
                ('name_en', models.CharField(help_text='Collection name in English.', max_length=255, verbose_name='Name (English)')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='True for system-defined collections (Alphabet, Numbers, etc.). These are included in every full sync for new clients.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Automatically updated on every save. Used as the sync cursor.')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-is_default', 'name_en'],
                'indexes': [models.Index(fields=['is_default', 'updated_at'], name='coll_default_updated_idx')],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_uz', models.CharField(max_length=255, verbose_name='Word (Uzbek)')),
                ('word_en', models.CharField(max_length=255, verbose_name='Word (English)')),
                ('image', models.ImageField(blank=True, help_text='Optional illustration for the word.', null=True, upload_to='words/images/%Y/%m/')),
                ('audio', models.FileField(blank=True, help_text='Pronunciation audio file (mp3 / ogg).', null=True, upload_to='words/audio/%Y/%m/')),
                ('is_approved', models.BooleanField(db_index=True, default=True, help_text='Approved words are visible to all clients. Set to False to hold a user submission for review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocabulary.collection')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='The user who submitted this word (null for seeded data).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['word_en'],
                'indexes': [models.Index(fields=['is_approved', 'updated_at'], name='word_approved_updated_idx'), models.Index(fields=['collection', 'is_approved'], name='word_collection_approved_idx')],
            },
        ),
    ]
